/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CameraControl: typeof import('./src/components/Gis/components/cameraControl.vue')['default']
    Desc: typeof import('./src/components/Editor/components/desc.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTree: typeof import('element-plus/es')['ElTree']
    FnEditor: typeof import('./src/components/FnEditor/index.vue')['default']
    FnPanel: typeof import('./src/components/FnEditor/components/fn-panel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowTable: typeof import('./src/components/ShowTable/index.vue')['default']
    Sign: typeof import('./src/components/Gis/sign.vue')['default']
    Tree: typeof import('./src/components/Editor/components/tree.vue')['default']
    Zoom: typeof import('./src/components/Gis/components/zoom.vue')['default']
  }
}
